<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>EasyEDA.Loader.UI</AssemblyName>
    <RootNamespace>LcscBridge.App</RootNamespace>
    <Version>0.3.0</Version>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LcscBridge.Core/LcscBridge.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
  </ItemGroup>
  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Compile Remove="App.xaml.cs" />
  </ItemGroup>
</Project>
