<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AltiumLcscBridge</AssemblyName>
    <RootNamespace>LcscBridge.App</RootNamespace>
    <Version>0.2.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LcscBridge.Core/LcscBridge.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
  </ItemGroup>
</Project>
